/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appit;

import controller.*;
import database.MysqlConnection;

import datos.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;


/**
 *
 * @author Alexander
 */
public class AppItFrame extends javax.swing.JFrame {

    /**
     * Creates new form AppItFrame
     */
    public AppItFrame() {
        initComponents();
        myInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fProyecto = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nProyecto = new javax.swing.JLabel();
        tProyecto = new javax.swing.JLabel();
        hEstimadas = new javax.swing.JLabel();
        fInicio = new javax.swing.JLabel();
        pTermino = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaProyecto = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        cProyecto = new javax.swing.JLabel();
        fCliente = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        proyectosCliente = new javax.swing.JTable();
        nCliente = new javax.swing.JLabel();
        rutCliente = new javax.swing.JLabel();
        razonCliente = new javax.swing.JLabel();
        dirCliente = new javax.swing.JLabel();
        cCliente = new javax.swing.JLabel();
        gCliente = new javax.swing.JLabel();
        fEmpleado = new javax.swing.JFrame();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        nEmpleado = new javax.swing.JLabel();
        aEmpleado = new javax.swing.JLabel();
        uEmpleado = new javax.swing.JLabel();
        rEmpleado = new javax.swing.JLabel();
        iEmpleado = new javax.swing.JLabel();
        fNuevoProyecto = new javax.swing.JFrame();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tProyectoBox = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        nombreP = new javax.swing.JTextField();
        npHorasEstimadas = new javax.swing.JTextField();
        npFechaInicio = new javax.swing.JTextField();
        npFechaTermino = new javax.swing.JTextField();
        nuevoProyectoBoton = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        npClienteBox = new javax.swing.JComboBox<>();
        npRecursoBoton = new javax.swing.JButton();
        npempeladoBoton = new javax.swing.JButton();
        addRecurso = new javax.swing.JFrame();
        addRecursoBox = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        addRecursoBoton = new javax.swing.JButton();
        addEmpleado = new javax.swing.JFrame();
        jLabel30 = new javax.swing.JLabel();
        addEmpleadoBox = new javax.swing.JComboBox<>();
        addEmpleadoBoton = new javax.swing.JButton();
        fNuevoCliente = new javax.swing.JFrame();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        ncRutCliente = new javax.swing.JTextField();
        ncNombreCliente = new javax.swing.JTextField();
        ncRazonSocial = new javax.swing.JTextField();
        ncGiroCliente = new javax.swing.JTextField();
        ncCorreo = new javax.swing.JTextField();
        ncDireccion = new javax.swing.JTextField();
        ncComunaBox = new javax.swing.JComboBox<>();
        ncRegistrarClienteBoton = new javax.swing.JButton();
        ncAddTelefonoBoton = new javax.swing.JButton();
        addTelefono = new javax.swing.JFrame();
        jLabel38 = new javax.swing.JLabel();
        ncTelefono = new javax.swing.JTextField();
        addTBoton = new javax.swing.JButton();
        fNuevoEmpleado = new javax.swing.JFrame();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        neNombre = new javax.swing.JTextField();
        neApellido = new javax.swing.JTextField();
        neUsuario = new javax.swing.JTextField();
        neContrasena = new javax.swing.JTextField();
        neSueldo = new javax.swing.JTextField();
        neDireccion = new javax.swing.JTextField();
        neComunaBox = new javax.swing.JComboBox<>();
        neRolBox = new javax.swing.JComboBox<>();
        neRegistrarBoton = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        neJefeBox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        proyectoLista = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        clienteLista = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        empleadoLista = new javax.swing.JList<>();
        nuevoProyecto = new javax.swing.JButton();
        nuevoCliente = new javax.swing.JButton();
        nuevoEmpleadoBoton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jLabel4.setText("Nombre Proyecto:");

        jLabel5.setText("Tipo Proyecto:");

        jLabel6.setText("Horas Estimadas:");

        jLabel7.setText("Fecha Inicio:");

        jLabel8.setText("Planificación Termino:");

        nProyecto.setText("123");

        tProyecto.setText("123");

        hEstimadas.setText("123");

        fInicio.setText("123");

        pTermino.setText("123");

        jLabel9.setText("Empleados asociados");

        tablaProyecto.setAutoCreateColumnsFromModel(false);
        jScrollPane4.setViewportView(tablaProyecto);

        jLabel10.setText("Cliente Proyecto:");

        cProyecto.setText("123");

        javax.swing.GroupLayout fProyectoLayout = new javax.swing.GroupLayout(fProyecto.getContentPane());
        fProyecto.getContentPane().setLayout(fProyectoLayout);
        fProyectoLayout.setHorizontalGroup(
            fProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fProyectoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(fProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addGroup(fProyectoLayout.createSequentialGroup()
                        .addGroup(fProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(29, 29, 29)
                        .addGroup(fProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fInicio)
                            .addComponent(pTermino)
                            .addComponent(hEstimadas)
                            .addComponent(tProyecto)
                            .addComponent(nProyecto)
                            .addComponent(cProyecto))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        fProyectoLayout.setVerticalGroup(
            fProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fProyectoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(fProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nProyecto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tProyecto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cProyecto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(hEstimadas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fInicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pTermino))
                .addGap(43, 43, 43)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jLabel11.setText("Nombre Cliente:");

        jLabel12.setText("Razon Social:");

        jLabel13.setText("Rut Cliente:");

        jLabel14.setText("Dirección:");

        jLabel15.setText("Correo:");

        jLabel16.setText("Giro:");

        jLabel17.setText("Proyectos asociados:");

        proyectosCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(proyectosCliente);

        nCliente.setText("jLabel18");

        rutCliente.setText("jLabel19");

        razonCliente.setText("jLabel20");

        dirCliente.setText("jLabel21");

        cCliente.setText("jLabel22");

        gCliente.setText("jLabel23");

        javax.swing.GroupLayout fClienteLayout = new javax.swing.GroupLayout(fCliente.getContentPane());
        fCliente.getContentPane().setLayout(fClienteLayout);
        fClienteLayout.setHorizontalGroup(
            fClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fClienteLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(fClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addGroup(fClienteLayout.createSequentialGroup()
                        .addGroup(fClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(fClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gCliente)
                            .addComponent(cCliente)
                            .addComponent(dirCliente)
                            .addComponent(razonCliente)
                            .addComponent(rutCliente)
                            .addComponent(nCliente))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        fClienteLayout.setVerticalGroup(
            fClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fClienteLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(fClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(rutCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(razonCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(dirCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(gCliente))
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel18.setText("Nombre Empleado:");

        jLabel19.setText("Apellido Empleado:");

        jLabel20.setText("Rol Emplado:");

        jLabel21.setText("Fecha Incorporación:");

        jLabel22.setText("Nombre de usuario:");

        nEmpleado.setText("jLabel23");

        aEmpleado.setText("jLabel23");

        uEmpleado.setText("jLabel23");

        rEmpleado.setText("jLabel23");

        iEmpleado.setText("jLabel23");

        javax.swing.GroupLayout fEmpleadoLayout = new javax.swing.GroupLayout(fEmpleado.getContentPane());
        fEmpleado.getContentPane().setLayout(fEmpleadoLayout);
        fEmpleadoLayout.setHorizontalGroup(
            fEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fEmpleadoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(fEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel22)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(32, 32, 32)
                .addGroup(fEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iEmpleado)
                    .addComponent(rEmpleado)
                    .addComponent(uEmpleado)
                    .addComponent(aEmpleado)
                    .addComponent(nEmpleado))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        fEmpleadoLayout.setVerticalGroup(
            fEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fEmpleadoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(fEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(nEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(aEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(uEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(rEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(iEmpleado))
                .addContainerGap(250, Short.MAX_VALUE))
        );

        jLabel23.setText("Nombre:");

        jLabel24.setText("Tipo Proyecto:");

        tProyectoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel25.setText("Horas estimadas:");

        jLabel26.setText("Fecha inicio:");

        jLabel27.setText("Fecha termino planificada:");

        nuevoProyectoBoton.setText("Añadir");

        jLabel28.setText("Cliente:");

        npClienteBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        npRecursoBoton.setText("Añadir Recurso");
        npRecursoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npRecursoBotonActionPerformed(evt);
            }
        });

        npempeladoBoton.setText("Añadir Empleado");
        npempeladoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npempeladoBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fNuevoProyectoLayout = new javax.swing.GroupLayout(fNuevoProyecto.getContentPane());
        fNuevoProyecto.getContentPane().setLayout(fNuevoProyectoLayout);
        fNuevoProyectoLayout.setHorizontalGroup(
            fNuevoProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fNuevoProyectoLayout.createSequentialGroup()
                .addGroup(fNuevoProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fNuevoProyectoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(fNuevoProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fNuevoProyectoLayout.createSequentialGroup()
                                .addGroup(fNuevoProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel23))
                                .addGap(66, 66, 66)
                                .addGroup(fNuevoProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tProyectoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(fNuevoProyectoLayout.createSequentialGroup()
                                .addGroup(fNuevoProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26))
                                .addGap(53, 53, 53)
                                .addGroup(fNuevoProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(npFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(npHorasEstimadas, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(fNuevoProyectoLayout.createSequentialGroup()
                                .addGroup(fNuevoProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(fNuevoProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(npClienteBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(npFechaTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(fNuevoProyectoLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(nuevoProyectoBoton))
                    .addGroup(fNuevoProyectoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(npRecursoBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(npempeladoBoton)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        fNuevoProyectoLayout.setVerticalGroup(
            fNuevoProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fNuevoProyectoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fNuevoProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(nombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fNuevoProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(tProyectoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fNuevoProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(npHorasEstimadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fNuevoProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(npFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fNuevoProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(npFechaTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fNuevoProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(npClienteBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(fNuevoProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npRecursoBoton)
                    .addComponent(npempeladoBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(nuevoProyectoBoton)
                .addGap(43, 43, 43))
        );

        addRecursoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel29.setText("Recurso:");

        addRecursoBoton.setText("Añadir");

        javax.swing.GroupLayout addRecursoLayout = new javax.swing.GroupLayout(addRecurso.getContentPane());
        addRecurso.getContentPane().setLayout(addRecursoLayout);
        addRecursoLayout.setHorizontalGroup(
            addRecursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRecursoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addGroup(addRecursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addRecursoBoton)
                    .addComponent(addRecursoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        addRecursoLayout.setVerticalGroup(
            addRecursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRecursoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(addRecursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRecursoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addRecursoBoton)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel30.setText("Empleado:");

        addEmpleadoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addEmpleadoBoton.setText("Añadir Empleado");

        javax.swing.GroupLayout addEmpleadoLayout = new javax.swing.GroupLayout(addEmpleado.getContentPane());
        addEmpleado.getContentPane().setLayout(addEmpleadoLayout);
        addEmpleadoLayout.setHorizontalGroup(
            addEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addComponent(addEmpleadoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addEmpleadoLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(addEmpleadoBoton)
                .addGap(48, 48, 48))
        );
        addEmpleadoLayout.setVerticalGroup(
            addEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmpleadoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(addEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(addEmpleadoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(addEmpleadoBoton)
                .addContainerGap())
        );

        jLabel31.setText("RUT Cliente:");

        jLabel32.setText("Nombre Cliente:");

        jLabel33.setText("Razon Social:");

        jLabel34.setText("Giro Cliente:");

        jLabel35.setText("Correo:");

        jLabel36.setText("Dirección:");

        jLabel37.setText("Comuna:");

        ncComunaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ncRegistrarClienteBoton.setText("Registrar");

        ncAddTelefonoBoton.setText("Añadir Telefono");

        javax.swing.GroupLayout fNuevoClienteLayout = new javax.swing.GroupLayout(fNuevoCliente.getContentPane());
        fNuevoCliente.getContentPane().setLayout(fNuevoClienteLayout);
        fNuevoClienteLayout.setHorizontalGroup(
            fNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fNuevoClienteLayout.createSequentialGroup()
                .addGroup(fNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fNuevoClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(fNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37))
                        .addGap(28, 28, 28)
                        .addGroup(fNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ncComunaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(fNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ncNombreCliente)
                                .addComponent(ncRutCliente)
                                .addComponent(ncRazonSocial)
                                .addComponent(ncGiroCliente)
                                .addComponent(ncCorreo)
                                .addComponent(ncDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))))
                    .addGroup(fNuevoClienteLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(ncRegistrarClienteBoton))
                    .addGroup(fNuevoClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ncAddTelefonoBoton)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        fNuevoClienteLayout.setVerticalGroup(
            fNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fNuevoClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(ncRutCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(ncNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(ncRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(ncGiroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(ncCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(ncDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fNuevoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(ncComunaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ncAddTelefonoBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(ncRegistrarClienteBoton)
                .addGap(27, 27, 27))
        );

        jLabel38.setText("Telefono Cliente:");

        addTBoton.setText("Añadir");

        javax.swing.GroupLayout addTelefonoLayout = new javax.swing.GroupLayout(addTelefono.getContentPane());
        addTelefono.getContentPane().setLayout(addTelefonoLayout);
        addTelefonoLayout.setHorizontalGroup(
            addTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTelefonoLayout.createSequentialGroup()
                .addGroup(addTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addTelefonoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ncTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addTelefonoLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(addTBoton)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        addTelefonoLayout.setVerticalGroup(
            addTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTelefonoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(ncTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(addTBoton)
                .addContainerGap())
        );

        jLabel39.setText("Nombre:");

        jLabel40.setText("Apellido: ");

        jLabel41.setText("Usuario:");

        jLabel42.setText("Contraseña:");

        jLabel44.setText("Sueldo:");

        jLabel43.setText("Dirección:");

        jLabel46.setText("Comuna:");

        jLabel47.setText("Rol:");

        neComunaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        neRolBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        neRegistrarBoton.setText("Registrar");

        jLabel48.setText("Jefe:");

        neJefeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout fNuevoEmpleadoLayout = new javax.swing.GroupLayout(fNuevoEmpleado.getContentPane());
        fNuevoEmpleado.getContentPane().setLayout(fNuevoEmpleadoLayout);
        fNuevoEmpleadoLayout.setHorizontalGroup(
            fNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fNuevoEmpleadoLayout.createSequentialGroup()
                .addGroup(fNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fNuevoEmpleadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(fNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel45)
                            .addGroup(fNuevoEmpleadoLayout.createSequentialGroup()
                                .addGroup(fNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel41))
                                .addGap(26, 26, 26)
                                .addGroup(fNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(neNombre)
                                    .addComponent(neApellido)
                                    .addComponent(neUsuario)))
                            .addGroup(fNuevoEmpleadoLayout.createSequentialGroup()
                                .addGroup(fNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel42)
                                    .addComponent(jLabel44)
                                    .addComponent(jLabel43)
                                    .addComponent(jLabel46)
                                    .addComponent(jLabel47)
                                    .addComponent(jLabel48))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(fNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(neContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(neSueldo)
                                    .addComponent(neDireccion)
                                    .addComponent(neComunaBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(neRolBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(neJefeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(fNuevoEmpleadoLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(neRegistrarBoton)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        fNuevoEmpleadoLayout.setVerticalGroup(
            fNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fNuevoEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(neNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(neApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(neUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(neContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(neSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(neDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(neComunaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(neRolBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fNuevoEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(neJefeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(neRegistrarBoton)
                .addGap(19, 19, 19))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Proyectos");

        proyectoLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(proyectoLista);

        jLabel2.setText("Clientes");

        clienteLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(clienteLista);

        jLabel3.setText("Empleados");

        empleadoLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(empleadoLista);

        nuevoProyecto.setText("Nuevo Proyecto");
        nuevoProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoProyectoActionPerformed(evt);
            }
        });

        nuevoCliente.setText("Nuevo Cliente");
        nuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoClienteActionPerformed(evt);
            }
        });

        nuevoEmpleadoBoton.setText("Nuevo Empleado");
        nuevoEmpleadoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoEmpleadoBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuevoProyecto))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuevoCliente))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nuevoEmpleadoBoton)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoProyecto)
                    .addComponent(nuevoCliente)
                    .addComponent(nuevoEmpleadoBoton))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoProyectoActionPerformed
        nombreP.setText("");
        npFechaInicio.setText("");
        npHorasEstimadas.setText("");
        npFechaTermino.setText("");
        
        Proyecto p = new Proyecto();
        p.setCodigoTipo(-1);
        String[] tipoProyecto = {"Pagina Web", "Aplicación Escritorio", "Aplicación Server", "Aplicación Móvil"};
        int[] tpCodigo = {1, 2, 3, 4}; // el codigo de tipo proyecto no encesariamente son numeros correlativos
        
        
        fNuevoProyecto.pack();
        fNuevoProyecto.setVisible(true);

        nuevoProyectoBoton.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                boolean ready = true;
                ArrayList<Recurso> res = new ArrayList<>();
                ArrayList<Empleado> emp = new ArrayList<>();
                String n = nombreP.getText();
                int h = -1;
                if(!tProyectoBox.getSelectedItem().toString().isEmpty()){
                    for (int i = 0; i < tipoProyecto.length; i++) {
                        if(tProyectoBox.getSelectedItem().toString().equalsIgnoreCase(tipoProyecto[i])){
                            h = tpCodigo[i];
                        }
                    }
                }
                else{
                    ready = false;
                }
                p.setCodigoTipo(h);
                if(!npClienteBox.getSelectedItem().toString().isEmpty()){
                    ArrayList<Cliente> cl = new ArrayList<>();
                    Cliente c = ClienteController.getClienteByNombre(npClienteBox.getSelectedItem().toString());
                    cl.add(c);
                    p.setClientes(cl);
                }
                else{
                    ready = false;
                }
                
                if (!npHorasEstimadas.getText().isEmpty()) {
                    h = Integer.parseInt(npHorasEstimadas.getText());
                }
                String fi = npFechaInicio.getText();
                String ft = npFechaTermino.getText();
                for(String r:npListaRecurso){
                    res.add(RecursoController.getRecursoByNombre(r));
                }
                
                for(int c:npListaEmpleado){
                    emp.add(EmpleadoController.getEmpleadoByCodigo(c));
                }                

                if(n.isEmpty())
                   ready = false;
                if(h == -1)
                    ready = false;
                if(fi.isEmpty())
                    ready = false;
                if(ft.isEmpty())
                    ready = false;
                if(p.getCodigoTipo() == -1)
                    ready = false;
                System.out.println(p.getCodigoTipo());

                if (ready){
                    
                    p.setNombre(n);
                    p.setHoraEstimada(h);
                    p.setFechaInicio(fi);
                    p.setFechaTerminoPlanificada(ft);
                    p.setRecursos(res);
                    p.setEmpleados(emp);
                    System.out.println("here");
                    ProyectoController.nuevoProyecto(p);
                    fNuevoProyecto.setVisible(false);
                    myInitComponents();
                }
                else{
                }
                
            }
        });
    }//GEN-LAST:event_nuevoProyectoActionPerformed

    private void npRecursoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npRecursoBotonActionPerformed

            ArrayList<Recurso> listaR = RecursoController.getRecursos();
            listaR.forEach(r -> {
            addRecursoBox.addItem(r.getNombre());
            });
            
            addRecurso.pack();
            addRecurso.setVisible(true);
            
            addRecursoBoton.addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent e){
                    npListaRecurso.add(addRecursoBox.getSelectedItem().toString());
                    addRecurso.setVisible(false);
                }
            });

    }//GEN-LAST:event_npRecursoBotonActionPerformed

    private void npempeladoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npempeladoBotonActionPerformed
        ArrayList<Empleado> listaE = EmpleadoController.getEmpleados();
        String[] listaEmpleado = new String [listaE.size()];
        String[][] le = new String [listaE.size()][2];
        addEmpleado.pack();
        addEmpleado.setVisible(true);
        for (int i = 0; i < listaE.size(); i++) {
            String cname = listaE.get(i).getNombre() + " " + listaE.get(i).getApellido();
            listaEmpleado[i] = cname;
            le[i][0] = cname;
            le[i][1] = Integer.toString(listaE.get(i).getCodigo());
        }
        
        for (int i = 0; i < listaEmpleado.length; i++) {
            addEmpleadoBox.addItem(listaEmpleado[i]);
        }
 
        addEmpleadoBoton.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                String emp = addEmpleadoBox.getSelectedItem().toString();
                if(!emp.isEmpty()){

                    for (int i = 0; i < listaEmpleado.length; i++) {
                        if(le[i][0].equalsIgnoreCase(emp)){
                            npListaEmpleado.add(Integer.parseInt(le[i][1]));
                            System.out.println(EmpleadoController.getEmpleadoByCodigo(Integer.parseInt(le[i][1])).getNombre());
                        }
                    }  
                } 
                addEmpleado.setVisible(false);
            }
        });
        
    }//GEN-LAST:event_npempeladoBotonActionPerformed

    private void nuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoClienteActionPerformed
        fNuevoCliente.pack();
        fNuevoCliente.setVisible(true);
        Cliente cliente = new Cliente();
        
        ArrayList<Comuna> comunas = ComunaController.getComunas();
        ArrayList<Integer> tel = new ArrayList<>();
        comunas.forEach(c -> {
            ncComunaBox.addItem(c.getNombre());
        });
        
        ncAddTelefonoBoton.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                ncTelefono.setText("");
                addTelefono.pack();
                addTelefono.setVisible(true);
            }
        });
        
        addTBoton.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                if(!ncTelefono.getText().isEmpty()){
                   tel.add(Integer.parseInt(ncTelefono.getText()));
                   addTelefono.setVisible(false);
                   addTelefono.dispose();
                }
                else{
                }
            }
        });
        
        ncRegistrarClienteBoton.addActionListener(new ActionListener(){
            boolean ready = true;

            @Override
            public void actionPerformed(ActionEvent e){
                String rut = ncRutCliente.getText();
                String nombre = ncNombreCliente.getText();
                String giro = ncGiroCliente.getText();
                String razon = ncRazonSocial.getText();
                String correo = ncCorreo.getText();
                String dir = ncDireccion.getText();
                String comuna = ncComunaBox.getSelectedItem().toString();
                
                Comuna c = ComunaController.getComunaByName(comuna);
                
                cliente.setRut(rut);
                cliente.setNombre(nombre);
                cliente.setGirocliente(giro);
                cliente.setRazonSocial(razon);
                cliente.setCorreo(correo);
                cliente.setDireccion(dir);
                cliente.setComuna(c);
                
                
                cliente.setTelefonos(tel);
                
                if (ready) {
                    ClienteController.nuevoCliente(cliente);
                    fNuevoCliente.setVisible(false);
                    fNuevoCliente.dispose();
                    myInitComponents();
                }
                else{
                    
                }
                
            }
        });
    }//GEN-LAST:event_nuevoClienteActionPerformed

    private void nuevoEmpleadoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoEmpleadoBotonActionPerformed
        
        ArrayList<Comuna> comunas = ComunaController.getComunas();
        ArrayList<Rol> roles = RolController.getRoles();
        ArrayList<Empleado> listaE = EmpleadoController.getEmpleados();
        String[][] le = new String [listaE.size()][2];

        for (int i = 0; i < listaE.size(); i++) {
            String cname = listaE.get(i).getNombre() + " " + listaE.get(i).getApellido();
            le[i][0] = cname;
            neJefeBox.addItem(cname);
            le[i][1] = Integer.toString(listaE.get(i).getCodigo());
        }
        
        comunas.forEach(c -> {
            neComunaBox.addItem(c.getNombre());
        });
        roles.forEach(r -> {
            neRolBox.addItem(r.getRol());
        });
        
        neRegistrarBoton.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                Empleado empleado = new Empleado();
                boolean ready = true;
                
                String name = neNombre.getText();
                String lastname = neApellido.getText();
                String user = neUsuario.getText();
                String pass = neContrasena.getText();
                String sSueldo = neSueldo.getText();
                String dir = neDireccion.getText();
                String jName = neJefeBox.getSelectedItem().toString();
                String nComuna = neComunaBox.getSelectedItem().toString();
                String nRol = neRolBox.getSelectedItem().toString();
                
                Comuna comuna = ComunaController.getComunaByName(nComuna);
                Rol rol = RolController.getRolByName(nRol);
                
                if(!sSueldo.isEmpty())
                        empleado.setSueldo(Integer.parseInt(sSueldo));
                    else
                        ready = false;
                
                if (ready) {
                    
                    empleado.setNombre(name);
                    empleado.setApellido(lastname);
                    empleado.setUsuario(user);
                    empleado.setContrasena(pass);
                    empleado.setDireccion(dir);
                    empleado.setComuna(comuna);
                    empleado.setRol(rol);
                    
                    if(!jName.isEmpty()){
                        for (int i = 0; i < le.length; i++) {
                            if(jName.equalsIgnoreCase(le[i][0])){
                                empleado.setEmpleado(EmpleadoController.getEmpleadoByCodigo(Integer.parseInt(le[i][1])));
                                break;
                            }
                        }
                    }

                    EmpleadoController.nuevoEmpleado(empleado);
                    fNuevoEmpleado.setVisible(false);
                    fNuevoEmpleado.dispose();
                }
            }
        });
        
        fNuevoEmpleado.pack();
        fNuevoEmpleado.setVisible(true);
        
    }//GEN-LAST:event_nuevoEmpleadoBotonActionPerformed
    public void myInitComponents() {
        proyectoLista.setName("proyecto");
        clienteLista.setName("cliente");
        empleadoLista.setName("empleado");
        proyectoLista.removeAll();
        MysqlConnection.conectar();
        ArrayList<Proyecto> listaP = ProyectoController.getProyectos();
        String[] listaProyectos = new String [listaP.size()];
        for (int i = 0; i < listaP.size(); i++) {
            listaProyectos[i] = listaP.get(i).getNombre();
        }
        proyectoLista.setListData(listaProyectos);
        tProyectoBox.removeAllItems();
        clienteLista.removeAll();
        ArrayList<Cliente> listaC = ClienteController.getClientes();
        String[] listaCliente = new String [listaC.size()];
        for (int i = 0; i < listaC.size(); i++) {
            listaCliente[i] = listaC.get(i).getNombre();
            
        }
        clienteLista.setListData(listaCliente);
        
        empleadoLista.removeAll();
        ArrayList<Empleado> listaE = EmpleadoController.getEmpleados();
        String[] listaEmpleado = new String [listaE.size()];
        String[][] le = new String [listaE.size()][2];

        for (int i = 0; i < listaE.size(); i++) {
            String cname = listaE.get(i).getNombre() + " " + listaE.get(i).getApellido();
            listaEmpleado[i] = cname;
            le[i][0] = cname;
            le[i][1] = Integer.toString(listaE.get(i).getCodigo());
        }
        empleadoLista.setListData(listaEmpleado);

        MouseListener ml = new MouseAdapter() {
            public void mouseClicked(MouseEvent me){
                JList jl = (JList) me.getSource();
                
                if (me.getClickCount() == 2){
                    int i = jl.locationToIndex(me.getPoint());
                     String name = "";

                    if (i >= 0){
                        Object o = jl.getModel().getElementAt(i);
                        name = o.toString();
                    }
                    switch(jl.getName()){
                        case "proyecto":
                            String tipo = "";
                            int horas = 0;
                            String iFecha = "";
                            String tFecha = "";
                            ArrayList<Empleado> empleados;
                            ArrayList<Cliente> cliente;
                            Proyecto p = ProyectoController.getProyectoByNombre(name);
                            fProyecto.setTitle(name);
                            nProyecto.setText(name);
                            tProyecto.setText(p.getTipoProyecto());
                            cliente = ProyectoController.getClientes(p.getCodigo());

                            if (cliente.size() > 0)
                                cProyecto.setText(cliente.get(0).getNombre());
                            else
                                cProyecto.setText("-");

                            hEstimadas.setText(Integer.toString(p.getHoraEstimada()));
                            fInicio.setText(p.getFechaInicio());
                            pTermino.setText(p.getFechaTerminoPlanificada());
                            fProyecto.pack();
                            fProyecto.setVisible(true);                          
                            break;
                        case "cliente":
                            Cliente c = ClienteController.getClienteByNombre(name);

                            String rut = c.getRut();
                            String dir = c.getDireccion();
                            String razon = c.getRazonSocial();
                            String giro = c.getGirocliente();
                            String correo = c.getCorreo();
                            
                            nCliente.setText(name);
                            
                            rutCliente.setText(rut);
                            dirCliente.setText(dir);
                            razonCliente.setText(razon);
                            gCliente.setText(giro);
                            cCliente.setText(correo);
              
                            fCliente.setTitle(name);
                            fCliente.pack();
                            fCliente.setVisible(true);
                            break;
                           
                        case "empleado":
                            int codigo = 0;

                            for (int index = 0; index < listaEmpleado.length; index++) {
                                
                                for (int j = 0; j < listaEmpleado.length; j++) {
                                    if (listaEmpleado[index].equalsIgnoreCase(le[j][0])) {
                                        codigo = Integer.parseInt(le[j][1]);
                                    }
                                }
                            }
                            
                            Empleado e = EmpleadoController.getEmpleadoByCodigo(codigo);
                            
                            String nombre = e.getNombre();
                            String apellido = e.getApellido();
                            String incorporacion = e.getIncorporacion();
                            String usuario = e.getUsuario();
                            String dire = e.getDireccion();
                            String rol = e.getRol().getRol();
                            
                            nEmpleado.setText(nombre);
                            aEmpleado.setText(apellido);
                            iEmpleado.setText(incorporacion);
                            uEmpleado.setText(usuario);
                            rEmpleado.setText(rol);
                            
                            fEmpleado.setTitle(name);
                            fEmpleado.pack();
                            fEmpleado.setVisible(true);
                            
                            break;
                    }
                }
            }
        };
        MysqlConnection.desconectar();

        proyectoLista.addMouseListener(ml);
        clienteLista.addMouseListener(ml);
        empleadoLista.addMouseListener(ml);
        String[] tipoProyecto = {"Pagina Web", "Aplicación Escritorio", "Aplicación Server", "Aplicación Móvil"};

        tProyectoBox.addItem("");
        for(String t: tipoProyecto){
            tProyectoBox.addItem(t);
        }
        
        npClienteBox.removeAllItems();
        npClienteBox.addItem("");
        listaC.forEach(c -> {
            npClienteBox.addItem(c.getNombre());
        });
        addRecursoBox.removeAllItems();
        addEmpleadoBox.removeAllItems();
        ncComunaBox.removeAllItems();
        ncComunaBox.addItem("");
        neComunaBox.removeAllItems();
        neRolBox.removeAllItems();
        neComunaBox.addItem("");
        neRolBox.addItem("");
        neJefeBox.removeAllItems();
        neJefeBox.addItem("");

   
        //for (int index = 0; index < listaEmpleado.length; index++) {
                                
        //    for (int j = 0; j < listaEmpleado.length; j++) {
        //        if (listaEmpleado[index].equalsIgnoreCase(le[j][0])) {
        //            codigo = Integer.parseInt(le[j][1]);
        //        }
        //    }
        //}
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppItFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppItFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppItFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppItFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppItFrame().setVisible(true);
            }
        });
    }
    private ArrayList<Integer> npListaEmpleado = new ArrayList<>();
    private ArrayList<String> npListaRecurso = new ArrayList<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aEmpleado;
    private javax.swing.JFrame addEmpleado;
    private javax.swing.JButton addEmpleadoBoton;
    private javax.swing.JComboBox<String> addEmpleadoBox;
    private javax.swing.JFrame addRecurso;
    private javax.swing.JButton addRecursoBoton;
    private javax.swing.JComboBox<String> addRecursoBox;
    private javax.swing.JButton addTBoton;
    private javax.swing.JFrame addTelefono;
    private javax.swing.JLabel cCliente;
    private javax.swing.JLabel cProyecto;
    private javax.swing.JList<String> clienteLista;
    private javax.swing.JLabel dirCliente;
    private javax.swing.JList<String> empleadoLista;
    private javax.swing.JFrame fCliente;
    private javax.swing.JFrame fEmpleado;
    private javax.swing.JLabel fInicio;
    private javax.swing.JFrame fNuevoCliente;
    private javax.swing.JFrame fNuevoEmpleado;
    private javax.swing.JFrame fNuevoProyecto;
    private javax.swing.JFrame fProyecto;
    private javax.swing.JLabel gCliente;
    private javax.swing.JLabel hEstimadas;
    private javax.swing.JLabel iEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel nCliente;
    private javax.swing.JLabel nEmpleado;
    private javax.swing.JLabel nProyecto;
    private javax.swing.JButton ncAddTelefonoBoton;
    private javax.swing.JComboBox<String> ncComunaBox;
    private javax.swing.JTextField ncCorreo;
    private javax.swing.JTextField ncDireccion;
    private javax.swing.JTextField ncGiroCliente;
    private javax.swing.JTextField ncNombreCliente;
    private javax.swing.JTextField ncRazonSocial;
    private javax.swing.JButton ncRegistrarClienteBoton;
    private javax.swing.JTextField ncRutCliente;
    private javax.swing.JTextField ncTelefono;
    private javax.swing.JTextField neApellido;
    private javax.swing.JComboBox<String> neComunaBox;
    private javax.swing.JTextField neContrasena;
    private javax.swing.JTextField neDireccion;
    private javax.swing.JComboBox<String> neJefeBox;
    private javax.swing.JTextField neNombre;
    private javax.swing.JButton neRegistrarBoton;
    private javax.swing.JComboBox<String> neRolBox;
    private javax.swing.JTextField neSueldo;
    private javax.swing.JTextField neUsuario;
    private javax.swing.JTextField nombreP;
    private javax.swing.JComboBox<String> npClienteBox;
    private javax.swing.JTextField npFechaInicio;
    private javax.swing.JTextField npFechaTermino;
    private javax.swing.JTextField npHorasEstimadas;
    private javax.swing.JButton npRecursoBoton;
    private javax.swing.JButton npempeladoBoton;
    private javax.swing.JButton nuevoCliente;
    private javax.swing.JButton nuevoEmpleadoBoton;
    private javax.swing.JButton nuevoProyecto;
    private javax.swing.JButton nuevoProyectoBoton;
    private javax.swing.JLabel pTermino;
    private javax.swing.JList<String> proyectoLista;
    private javax.swing.JTable proyectosCliente;
    private javax.swing.JLabel rEmpleado;
    private javax.swing.JLabel razonCliente;
    private javax.swing.JLabel rutCliente;
    private javax.swing.JLabel tProyecto;
    private javax.swing.JComboBox<String> tProyectoBox;
    private javax.swing.JTable tablaProyecto;
    private javax.swing.JLabel uEmpleado;
    // End of variables declaration//GEN-END:variables
}
