/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appit;

import controller.ClienteController;
import datos.Cliente;
import javax.swing.JFrame;

/**
 * Vista de información del Cliente
 * @author Alexander
 */
public class FCliente extends javax.swing.JFrame {
    private String name;
    /**
     * Constructor de la vista
     * 
     * @param name El parametro name define el titulo de la vista y ayuda a la busqueda de elementos en la base de datos
     */
    public FCliente(String name) {
        this.name = name;
        initComponents();
        myInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        razonCliente = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dirCliente = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cCliente = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        gCliente = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        nCliente = new javax.swing.JLabel();
        rutCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel11.setText("Nombre Cliente:");

        razonCliente.setText("jLabel20");

        jLabel12.setText("Razon Social:");

        dirCliente.setText("jLabel21");

        jLabel13.setText("Rut Cliente:");

        cCliente.setText("jLabel22");

        jLabel14.setText("Dirección:");

        gCliente.setText("jLabel23");

        jLabel15.setText("Correo:");

        jLabel16.setText("Giro:");

        nCliente.setText("jLabel18");

        rutCliente.setText("jLabel19");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gCliente)
                    .addComponent(cCliente)
                    .addComponent(dirCliente)
                    .addComponent(razonCliente)
                    .addComponent(rutCliente)
                    .addComponent(nCliente))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(rutCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(razonCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(dirCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(gCliente))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Inicialización de componentes
     */
    private void myInit(){
        this.setTitle(this.name);
        System.out.println(this.name);
        Cliente c = ClienteController.getClienteByNombre(this.name);

        String rut = c.getRut();
        String dir = c.getDireccion();
        String razon = c.getRazonSocial();
        String giro = c.getGirocliente();
        String correo = c.getCorreo();
                            
        nCliente.setText(this.name);
                            
        rutCliente.setText(rut);
        dirCliente.setText(dir);
        razonCliente.setText(razon);
        gCliente.setText(giro);
        cCliente.setText(correo);
                  
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cCliente;
    private javax.swing.JLabel dirCliente;
    private javax.swing.JLabel gCliente;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel nCliente;
    private javax.swing.JLabel razonCliente;
    private javax.swing.JLabel rutCliente;
    // End of variables declaration//GEN-END:variables
}
