/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appit;

import controller.EmpleadoController;
import datos.Empleado;
import javax.swing.JFrame;

/**
 * Vista de información del Empleado
 * @author Alexander
 */
public class FEmpleado extends javax.swing.JFrame {
    String name;
    String[] listaEmpleado;
    String[][] le;
    /**
     * Creates new form FEmpleado
     */
    public FEmpleado(String name, String[] listaEmpleado, String[][] le) {
        this.name = name;
        this.listaEmpleado = listaEmpleado;
        this.le = le;
        initComponents();
        myInit();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aEmpleado = new javax.swing.JLabel();
        uEmpleado = new javax.swing.JLabel();
        rEmpleado = new javax.swing.JLabel();
        iEmpleado = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        nEmpleado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        aEmpleado.setText("jLabel23");

        uEmpleado.setText("jLabel23");

        rEmpleado.setText("jLabel23");

        iEmpleado.setText("jLabel23");

        jLabel18.setText("Nombre Empleado:");

        jLabel19.setText("Apellido Empleado:");

        jLabel20.setText("Rol Emplado:");

        jLabel21.setText("Fecha Incorporación:");

        jLabel22.setText("Nombre de usuario:");

        nEmpleado.setText("jLabel23");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel22)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iEmpleado)
                    .addComponent(rEmpleado)
                    .addComponent(uEmpleado)
                    .addComponent(aEmpleado)
                    .addComponent(nEmpleado))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(nEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(aEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(uEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(rEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(iEmpleado))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myInit(){
        this.setTitle(this.name);
        
        int codigo = 0;

        for (int index = 0; index < this.listaEmpleado.length; index++) {
                                
            for (int j = 0; j < this.listaEmpleado.length; j++) {
                if (this.listaEmpleado[index].equalsIgnoreCase(this.le[j][0])) {
                    codigo = Integer.parseInt(this.le[j][1]);
                }
            }
        }
                            
        Empleado e = EmpleadoController.getEmpleadoByCodigo(codigo);
                            
        String nombre = e.getNombre();
        String apellido = e.getApellido();
        String incorporacion = e.getIncorporacion();
        String usuario = e.getUsuario();
        String dire = e.getDireccion();
        String rol = e.getRol().getRol();
                            
        nEmpleado.setText(nombre);
        aEmpleado.setText(apellido);
        iEmpleado.setText(incorporacion);
        uEmpleado.setText(usuario);
        rEmpleado.setText(rol);
        
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aEmpleado;
    private javax.swing.JLabel iEmpleado;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel nEmpleado;
    private javax.swing.JLabel rEmpleado;
    private javax.swing.JLabel uEmpleado;
    // End of variables declaration//GEN-END:variables
}
