/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appit;

import controller.ProyectoController;
import datos.Cliente;
import datos.Empleado;
import datos.Proyecto;
import java.util.ArrayList;
import javax.swing.JFrame;

/**
 * Vista de información del proyecto y finalización el mismo
 * @author Alexander
 * @version %I% %G%
 */
public class FProyecto extends javax.swing.JFrame {

    /**
     * Contructor que inicializa todos los componentes
     */
    private String name;
    public FProyecto(String name) {
        this.name = name;
        initComponents();
        myInit(); //inicia componentes
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nProyecto = new javax.swing.JLabel();
        tProyecto = new javax.swing.JLabel();
        hEstimadas = new javax.swing.JLabel();
        fInicio = new javax.swing.JLabel();
        pTermino = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cProyecto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        finalizarProyectoBoton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("Fecha Inicio:");

        jLabel8.setText("Planificación Termino:");

        nProyecto.setText("123");

        tProyecto.setText("123");

        hEstimadas.setText("123");

        fInicio.setText("123");

        pTermino.setText("123");

        jLabel10.setText("Cliente Proyecto:");

        jLabel4.setText("Nombre Proyecto:");

        cProyecto.setText("123");

        jLabel5.setText("Tipo Proyecto:");

        finalizarProyectoBoton.setText("Finalizar Proyecto");
        finalizarProyectoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarProyectoBotonActionPerformed(evt);
            }
        });

        jLabel6.setText("Horas Estimadas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(finalizarProyectoBoton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fInicio)
                            .addComponent(pTermino)
                            .addComponent(hEstimadas)
                            .addComponent(tProyecto)
                            .addComponent(nProyecto)
                            .addComponent(cProyecto))))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nProyecto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tProyecto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cProyecto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(hEstimadas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fInicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pTermino))
                .addGap(67, 67, 67)
                .addComponent(finalizarProyectoBoton)
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finalizarProyectoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarProyectoBotonActionPerformed
        System.out.println("hi");
    }//GEN-LAST:event_finalizarProyectoBotonActionPerformed
    
    /**
     * Iniciación de componentes
     */
    private void myInit(){
        
        this.setTitle(name);
        
        ArrayList<Empleado> empleados;
        ArrayList<Cliente> cliente;
        Proyecto p = ProyectoController.getProyectoByNombre(this.name);
        cliente = ProyectoController.getClientes(p.getCodigo());

        nProyecto.setText(this.name);
        tProyecto.setText(p.getTipoProyecto());

        if (cliente.size() > 0)
            cProyecto.setText(cliente.get(0).getNombre());
        else
            cProyecto.setText("-");

        hEstimadas.setText(Integer.toString(p.getHoraEstimada()));
        fInicio.setText(p.getFechaInicio());
        pTermino.setText(p.getFechaTerminoPlanificada());
        finalizarProyectoBoton.setName(this.name);
        
       this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cProyecto;
    private javax.swing.JLabel fInicio;
    private javax.swing.JButton finalizarProyectoBoton;
    private javax.swing.JLabel hEstimadas;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel nProyecto;
    private javax.swing.JLabel pTermino;
    private javax.swing.JLabel tProyecto;
    // End of variables declaration//GEN-END:variables
}
